### ISSUE TITLE
Summary stats: new items, reformat, some refactor

### ISSUE THREAD

**Issue by tevpg** [ironwoodcall/TagTracker#11]
calc_stays passes a list back but also a bunch of info through side-effect globals that are set here and then read in the caller. 
 This seems messy.  Stats calculations should be refactored.  

Also I think stats should include all bikes, not just those that have been returned to owners.  Consider this as an example:
- We have two bikes on hand. Both arrived at 9am.  One returned out at 10am, the other is still here (e.g. at 13:30).
- I contend that the longest stay is 4.5 hours (the bike still here), not 1 hr.
- I would want the stats report though to say something like "As at 13:30, with <i>x</i> bikes still on hand."

**Comment by ironwoodcall** [comment]
I agree, these would all be good changes and would improve stats' accuracy

**Comment by tevpg** [comment]
This now includes adding additional stats to the summary page (busiest times, most bikes on hand, queue/stack) from #8, which I am closing as a duplicate.

Proposed format (to keep compact on that small screen):
```
Summary statistics at HH:MM (2 bike(s) still at valet):

Bike check-ins:      Stays:
  Total:   107         < 1.5h:      26
  AM:       49         1.5-5.0h:    51
  PM:       58         >5.0h:       30
  Regular:  64         Max:      11:13 [tag(s) wb3]
  Oversize: 43         Min:      00:01 [tag(s) wc10, we13, we12]
                       Median:   02:33
                       Mode:     02:00 (by 2 bikes, 30 minute blocks)

Most bikes on hand at valet:
                Regular  Oversize  Total  Time
Most regular:      60       20       80    10:15,14:30
Most oversize:     42       31       73    13:11
Most combined:     55       29       84    13:55

Most bike transactions:
            CheckedIn  Out   Total
09:30-10:00      45      0      45
16:00-16:30       5     39      44
08:00-08:30      37      0      37

Stays were 47% queue-like, 53% stack-like
```

**Comment by tevpg** [comment]
This currently is implemented as far as 'most bikes on hand' but not yet 'busiest time of day', in [pull request 67](https://github.com/ironwoodcall/TagTracker/pull/67), which has been merged into main.

**Comment by tevpg** [comment]
Finished with [pull request 70](https://github.com/ironwoodcall/TagTracker/pull/70)
