### ISSUE TITLE
File formats

### ISSUE THREAD

**Issue by tevpg** [ironwoodcall/TagTracker#13]
I would like to change the logfile format:
- each file start with a # line saying its time/date created.
- each line would be HH:MM,{tag},IN|OUT (more robust format)
- filenames would be more like 'tagtracker_YYYY-MM-DD.log' than just date [the root should prob be a config item]
- maybe only rewrite the file when the data changes (checkin/out/edit/delete functions would mark the data as 'dirty' - but this seems unneccessary)
- ignore blank lines and any lines that start with '#'.  Not sure I can even justify that, I just always want to be able to put comment lines into files.
- maybe each file end with "# EOF" marker (edited)

I would like to change the tag config file format:
- ignore blank lines and any lines that start with '#', and any other lines would have to match a tag pattern, e.g. "^ \*[a-zA-Z][a-zA-Z]0\*[1-9][0-9]\* \*$" 
- allow multiple tags on a line, whitespace (or comma) separated

For all config files:
- remove embedded whitespace from the filenames, just use snake case (e.g. "normal_tags.cfg") (e

**Comment by ironwoodcall** [comment]
Changed tag config file formats in branch julias-doing-fixes. 

Probably efficient to refactor or rewrite read_tags() at the same time as changing the logfile format in future

**Comment by tevpg** [comment]
Suggest leaving logfile format as-is for now; concentrate on archive format, and tool to convert logfile format into archive format.

**Comment by ironwoodcall** [comment]
All proposed changes (& more) implemented, including tags lists context storage in day's logfiles
