### ISSUE TITLE
Refactor DB management

### ISSUE THREAD

**Issue by ironwoodcall** [ironwoodcall/TagTracker#180]
Database updater script needs a reorg. Currently contains all of constants, database creation, and database updating.
Working on:
- [x] split DB creation into new file `make_tables.sql`

**Comment by tevpg** [comment]
As you might imagine I strongly encourage that you use a sql script for
database creation not a Python script.

**Comment by ironwoodcall** [comment]
Addressed in branch feat/180/db-reorg

**Comment by ironwoodcall** [comment]
merged into main
