### ISSUE TITLE
DB integrity checks

### ISSUE THREAD

**Issue by ironwoodcall** [ironwoodcall/TagTracker#181]
Would be good to:
- Check for properly formed records before committing new data to the DB
- Look for already-committed bad data -- this could also be a different script and cron job from the DB updater if we want it to run with different frequency

**Comment by tevpg** [comment]
Many of the bad data checks can get built right into the database as
“database constraints”, which make it impossible to insert bad data.

**Comment by tevpg** [comment]
Past this now
