### ISSUE TITLE
All published reports require datestamps

### ISSUE THREAD

**Issue by tevpg** [ironwoodcall/TagTracker#187]
Oddall situation today - people appear to have never connected computer to inet today, so "audit.txt" (& other published reports) are from yesterday.  Presumably people will notice it's not the same, but would still be good to put a datestamp at top of *all* published reports in order to decrease the odds of error.

Also: instead of "as at 24:00", should say (as a special case), "projected to end of day"

**Comment by ironwoodcall** [comment]
Hadn't occurred to me but I agree this is probably a good idea to reduce confusion

**Comment by tevpg** [comment]
Taking a look I see that it’s only an issue for the audit report
