### ISSUE TITLE
DB changes (was: needs OVERSIZE, REGULAR lists)

### ISSUE THREAD

**Issue by tevpg** [ironwoodcall/TagTracker#211]
In order to be able to do things like recreate standard reports for days in the past.

Suggest table: TAGLISTS
date: 
tagtype: 'RETIRED', 'OVERSIZE', 'REGULAR'
tags: text list, e.g. "wa1 wa0 wa3 oa4 oa3"

Up to three records per date; unique by combination of date+tagtype

**Comment by ironwoodcall** [comment]
Why not just have a column for each tagtype? 

This way we could get a day's oversized tags by doing eg. `SELECT oversize FROM taglists WHERE date == <date>;`, rather than giving each date multiple rows, which seems counterintuitive.

Makes more sense to my brain at least.

**Comment by tevpg** [comment]
Yup seems fine

**Comment by tevpg** [comment]
But also wonder what you think about the idea of calculated leftover in the day table, being a different column than assigned leftover. Maybe it’s too fussy, but one is an arbitrary number that comes from the day end form and the other is derived from the visit table. Using the same column h for both could arguably be semantically overloading the field

**Comment by ironwoodcall** [comment]
Ok so just to collate this into a todo list for myself:
### Summary of changes to be made based on this and Jul 10 email from SW
- [ ] In `visit`: `temp_10am` -> `temp` (becomes daily high)
- [ ] In `day`: potentially split `leftover` into "calculated" and "reported" columns
- [ ] New table `taglist` (text lists here to be parsed by TT reading in lists from .db:
```
date    | retired     | oversize    | regular
text PK | text (list) | text (list) | text (list)
```

**Comment by ironwoodcall** [comment]
Complete in branch `cleanup/251/tracker2db-changes`
