### ISSUE TITLE
cleanup

### ISSUE THREAD

**Issue by tevpg** [ironwoodcall/TagTracker#244]
- [x] replace calls to get_date() and similar deprecated/superseded functions with calls to date_str()
- [x] <s>replace `get_date()` in tracker2db.py with `date_str('today')`</s>
- [x] do a careful pull onto laptop minding the fact that valet_hours() is now in config
- [x] make sure all the following have hashbangs, +x, and LF line-ends:
  - [x] tagtracker.py
  - [x] dbupdate.py
  - [x] tracker2db.py
  - [x] cgi-reports.py
  - [x] fullness_alert.py (or whatever it's called)
- [x] scan database for valet-hours that don't meet expectations
- [x] #245

**Comment by ironwoodcall** [comment]
Self-assigned to have this appear in "my issues"
