### ISSUE TITLE
python datetime.weekday() not same as linux day of week!!! or its own

### ISSUE THREAD

**Issue by tevpg** [ironwoodcall/TagTracker#248]
This is hard to fathom:
```
>>> import datetime
>>> d = datetime.datetime.strptime("2023-07-13","%Y-%m-%d")
>>> d.weekday()
3
>>> d.strftime("%w")
'4'
>>>
```

- strftime() matches linux numbering
- weekday() is its own oddball thing
- and then there is ISO8601, which standardizes Mon-Sun as 1-7

So, being a vocal advocate of ISO8601 I pretty much have to say let's conform to ISO

So: change dt.weekday() to dt.isoweekday() and adjust lookups etc accordingly.

To Do:
- [x] @ironwoodcall this also affects cityhall_bikevalet.db:DAY.WEEKDAY - fortunately, I'm not aware of anything that (currently) uses that column
- [x] @tevpg this affects (new) tt_conf.py; (old) tt_util.py

**Comment by ironwoodcall** [comment]
Oh nice, love how many different ways there are to do this. I'll go in and change the `weekday` column again lol
