### ISSUE TITLE
convert spreadsheet records to compatible format

### ISSUE THREAD

**Issue by tevpg** [ironwoodcall/TagTracker#25]
Convert the existing google sheets daily tracking data to textfile format compatible with to-be bulk analysis tools (issue #7 ) 

Proposed Method
- old records are in google sheets.  downloaded to excel, unhide all the sheets, then (one by one ugh) save as csv (nb: ^C the UL cell, then paste that as filename; allows the whole thing to be fairly brainless keyboard-only task, at least in libre office)
- script would grab date from line 1; then for lines that match pattern, create tags records. 
- Ideas for what time within the half-hour block to use as tag time:
   - make them all at the beginning of the time block
   - spread them evenly within the time block (depend how many) --> though need to handle the edge case of > 30 tags [has this ever happened?] 
   - place them at 1-minute intervals starting at beginning of time block
   - possibly write some info at top of file in comments like: unmatched tags, this converted from csv, etc

**Comment by ironwoodcall** [comment]
What I've done previously for this is log everything from a block at the time exactly halfway through it. Would be about as good to put everything at the start of every block, just might shift average in or out times. 

I feel like the option of spreading events evenly within a block could give the appearance of precision that doesn't exist, so I'm leaning away from that as I don't think the little extra complexity wouldn't be worth it.

**Comment by tevpg** [comment]
Additional considerations:
1. The order in which the tags appear on the spreadsheet gives us an idea (statistically, not inerrant) of the order in which we processed bikes. I would like to preserve that information.  (Part of my desire there is to selfishly support the queue-like/stack-like analysis: if bike A and bike B arrive simultaneously but leave at different times, then is it queue-like or stack-like?  Can't tell.  But if we know bike A arrived <i>before</i> bike B, then we can make a determination.  I know there will, regardless, be some bikes that do arrive/leave simultaneously, but I wouldn't hate keeping the number down.)
2. Zero-duration stays.  Ugh, I hate these.  A bike arrives at 13:04 and leaves at 13:28.  Both are in the same block, so end up as in:13:15, out:13:15, a stay of 0 minutes.

Also have to say, the appearance of precision doesn't bother me, as I don't think anyone will be looking at individual records, just summary stats, and by retaining order we are increasing the accuracy of the rollups.

Suggestions:
1. Record all the bikes as checked in at 10 minutes into the block, and out at 20 minutes into the block.  (Or 14' and 16', or whatever.)  This helps with (2) though not (1)
2. Increase time granularity to seconds or sub-seconds (for internal representation, not for I/O).  E.g. store time internally as "minutes since midnight" or time objects (see #16). I had been thinking int but could as easily be float. Thus, bikes can arrive at 13:15.00001, 13:15.00002, 13:15.0003, and out at 13:15.00101, 13:15,00102, etc.  This addresses (1) but not (2)
3. Arbitrarily set any stay of <0:01 to be 0:01 when doing rollups.  Addresses (2) but not (1)

I suggest we do all three of these, in this order: 3, 1, 2.

**Comment by tevpg** [comment]
Here's a sample csv file created by saving a single page of the overall google tracking spreadsheet as csv.

[2023-04-10.csv](https://github.com/ironwoodcall/TagTracker/files/11444433/2023-04-10.csv)

Here's what I think the parser needs to do:
- see if the file exists
- parse the date from the first line
- build check_ins and check_outs dictionaryies, using time-assignment logic as above
- crawl through them looking for *and resolving* data issues

- write logfile in conventional format
  - include commented timestamp at top of file
  - include comment at top that this was generated from [input file], with datestamp
  - honestly, may as well include (commented) issues found
- display issues encountered, also write to .txt file

**Comment by tevpg** [comment]
More: this could be an important part of implementation, too.  If a person can easily convert today's partly-done sheet into tagtracker format, then we could start using tagtracker partway through a day.  For that matter, a person not on-site could help demonstrate the value of it by doing a conversion at their place, running (e.g.) an audit report, and passing it to the team at city hall valet.

Ideally would be able to go the other way too (from tagtracker format to spreadsheet) but that is somewhat fussier.  I suspect that anyone comfortable doing that would be comfortable simply using tagtracker.  Although there is a use case: a tagtracker-friendly person uses tagtracker in the morning, then populates the spreadsheet at handover (for a presumably not-tagtracker-friendly person in the afternoon)

**Comment by tevpg** [comment]
Addressing this in branch https://github.com/ironwoodcall/TagTracker/tree/feat/25/spreadsheet-converter

**Comment by tevpg** [comment]
More requirements, coming from [usage notes 2023-05-24](https://github.com/ironwoodcall/TagTracker/wiki/Usage-notes-2023-05-24) (in wiki)

- workflow is quite hairy.  
  - Current: 
    - google sheets saves to a nasty filename, 
    - then rename (e.g. "today.csv"); 
    - move to TT dir, where (unnoticed by me) it was magiaclly renamed to "today(2).csv"
    - csv2tracker which created a TT file in current dir, 
    - move to logs dir. Ugh.  Incredibly prone to error. 
  - better maybe: 
    - without args, looks in system Downloads dir for the ugly Google download, converts that and puts in logs dir (warning on overwrite)
    - with args: reads list of filenames, converts each, but without renaming to full LOG_BASENAME style - just dates, and maybe back in the source directory?
- does not identify/reject tags in the retired list. Is this good or bad?  (NB check that reading of tag lists is in util - also linesplit() fn, per #108)
  - desired behaviour: let them in then let lint-check flag it for correction
- has a bug which I keep changing on-site something like where tests for `len(messages[oldfile]` which fails if no oldfile key in messages
