### ISSUE TITLE
Crashes when ECHO (& PUBLISH) remote folders not available

### ISSUE THREAD

**Issue by ironwoodcall** [ironwoodcall/TagTracker#256]
```
TagTracker by Julias Hocking
  Version 0.8.9 (9d61a83 main)
  
  Creating new datafile ../data/cityhall_2023-07-17.dat.
  No inconsistencies found
  
  Please check today's opening/closing times.
  
  Bike Valet information for Monday July 17 (2023-07-17)
  Opening time is: 07:30
  Closing time is: 18:00
  New valet opening time (24 hour clock HHMM or <Enter> to cancel) >>> 0730
  Opening time now set to 07:30
  New valet closing time (24 hour clock HHMM or <Enter> to cancel) >>> 1800
  Closing time now set to 18:00
  
               ╭──────────╮             
     FREE      │ 🚲🚲🛴🚲 │     BIKE    
     SAFE     🔒 🚲🚲🚲🛴 │     VALET   
               ╰──────────╯             
  
  
  7:12  Bike tag or command >>> wa0
  Bike wa0 checked in                      <---in---  
tt_datafile:write_datafile():406: PROBLEM: Unable to create datafile '/mnt/chromeos/GoogleDrive/MyDrive/tracker_data/reports/cityhall_2023-07-17.dat'
  ERROR PUBLISHING DATAFILE
  REPORT PUBLISHING TURNED OFF
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bikevalet/TagTracker/tagtracker.py", line 1135, in <module>
    main()
  File "/home/bikevalet/TagTracker/tagtracker.py", line 974, in main
    pr.echo_flush()
  File "/home/bikevalet/TagTracker/tt_printer.py", line 105, in echo_flush
    set_echo(False)
  File "/home/bikevalet/TagTracker/tt_printer.py", line 79, in set_echo
    _echo_file.close()
OSError: [Errno 107] Transport endpoint is not connected
```

**Comment by tevpg** [comment]
That’s pretty weird.  It means that the Chromebook’s file system was not
accessible to the virtual machine.  I’m not sure what the correct behaviour
would be there.  Crashing might not be the worst?

What do we do when the OS is at fault?

**Comment by ironwoodcall** [comment]
Hmm, really doesn't seem like something we can fix then. JM told me it happens from time to time and a restart of TT always fixes it, which it did this time. It even correctly logged the check-in before crashing so no data was prevented from being recorded. Thinking a "wontfix" designation might be in order

**Comment by tevpg** [comment]
Maybe we can make it more elegant at least.

It uses those remote mounts to publish data, which we used to make the web
reports, so it’s pretty important.

Not critical for tracking the tags, but important for the overall data flow.

So maybe identify that it is There (the problem), and then suggest a
restart?

Let’s leave the issue open for a bit while we think about what would be the
desired behavior.

**Comment by ironwoodcall** [comment]
Yes, having it at least look less intimidating when this happens would probably be a good move. 

We could even automatically do a restart after a time delay for the OS to get ready, but that seems potentially excessive. Plus we'd have to take care not to lock in an infinite loop if things are mysteriously busted and don't fix themselves... And it's extremely easy to just restart normally.

It would be interesting if this happens consistently with a certain set of operator actions. If that's the case then we could have the error message suggest operating it in a way that won't cause the error, ie "try waiting 5 seconds between linux being ready and starting TT". Maybe also overkill

**Comment by tevpg** [comment]
Problem with automatic restart is, when do you stop doing it? At some point have to get on with life without PUBLISH or ECHO capabilities.  Going down that road, it would be something like:
- "hey, try restarting and if you get this again, then restart `startup --nopublish --noecho`"

For the nonce, I think maybe we add something like this to startup:
```
echo Starting tagtracker... this will take a few seconds...
sleep 10
cd ~/TagTracker
python3 tagtracker.py (etc)
```
which has the virtue of being way less work.

(Of course, we will still want to die gracefully when the error occurs.)

**Comment by tevpg** [comment]
- this still happens but not often
