### ISSUE TITLE
Usability tweak ideas

### ISSUE THREAD

**Issue by ironwoodcall** [ironwoodcall/TagTracker#265]
- Change return-out confirmation time to 10 minutes (from 30) - confirmations for times longer than this seem consistently not useful

- Input processing: strip characters from input text such as `\` and `]` that are frequently bumped while pressing the Enter key, and have no real meaning in the tracker workflow

**Comment by tevpg** [comment]
Item (1) above is a config item, so I changed that in TT's config & presumably it will magically be changed next time folks restart TT.

Item (2) - I agree & it's so tiny I suggest I just bundle it into the changes I'm making right now to your DB branch
