### ISSUE TITLE
Edit when only check-IN recorded

### ISSUE THREAD

**Issue by ironwoodcall** [ironwoodcall/TagTracker#31]
Crashes because when editing a check-in, the Tracker checks whether the proposed new event time is later than an existing check out to prevent physically unfeasible negative-duration stays. Predictably, this throws a KeyError when no check-out event exists to find.

**Comment by ironwoodcall** [comment]
fixed by having that test only run if the tag has checked out

**Comment by tevpg** [comment]
Looks like you've made the fix in a branch (awesome!)?  Will leave this open until you pull/merge the branch back into main.

Nice little bug!

**Comment by ironwoodcall** [comment]
Will do a pass to fix instances of this and keep it in mind
