### ISSUE TITLE
use fix_hhmm

### ISSUE THREAD

**Issue by tevpg** [ironwoodcall/TagTracker#37]
fix_hhmm can replace valid_time plus some of the time parsing that happens around it.  Can use to check times when reading log, checking input, etc.

Right now valid_time() is stubbed to simply call fix_hhmm; once things that call it are updated it can be removed.

fix_hhmm is implemented in branch 

```
    def fix_hhmm(inp:str) -> str:
    """Convert a string that might be a time to HH:MM (or to "")

    Return is either "" (doesn't look like a valid time) or
    will be HH:MM, always length 5 (i.e. 09:00 not 9:00)
    """
```

**Comment by ironwoodcall** [comment]
Closing this as was merged into main
