### ISSUE TITLE
stats for multi-day

### ISSUE THREAD

**Issue by tevpg** [ironwoodcall/TagTracker#51]
Update: combine multiple logfiles into single archive (csv or sqlite3).

Sample dialog:
```
$ this_script *.log cityhall2023.sqlite3
'Cityhall2023.sqlite3' does not exist.  Create new? (y/N): y
Creating archive
Adding data for:
  2023-05-01
  2023-05-02
  2023-05-03
Done.

$  this_script *.log cityhall2023.sqlite3
Adding data for:
   2023-05-04
   2023-05-06
This will REPLACE data for:
   2023-05-03
Proceed? (y/N): y
Done

$
```

Proposed data structure (if in database):
`DATE, TIME, TAG, INOUT, TIMESTAMP, BATCH`
Where:
- `DATE` and `TIME` are separated ISO8601 date & time
- `INOUT` is the text "IN" or "OUT"
- `TIMESTAMP` is ISO8601 text (e.g. "2023-05-03 14:00") for easy database manipulation, set by trigger from DATE and TIME
- `BATCH` uniquely identifies the records that were updated at a particular use of the script; suggested YYYYMMDDHHMMSS when the script was invoked
With integrity constraint
- UNIQUE DATE+TAG+INOUT (Can't have more than one in or out record for a given tag on a given day)

Original:
A separate script that would process multiple logs to
- produce multi-day summary stats &/or
- produce csv files of data in excel-friendly structure for analysis & charting

**Comment by tevpg** [comment]
Suggest focus on converting logfile format to archive format, not change logfile format (for now at least)

**Comment by ironwoodcall** [comment]
Addressed by database shenanigans
