### ISSUE TITLE
database structure

### ISSUE THREAD

**Issue by tevpg** [ironwoodcall/TagTracker#82]
- include a separate table of `DAILY_SUMMARY` (or something like that).  Opening and closing times can now be read from the logfile.  Other stuff is TBD regarding how it gets in here. (Day end form? Ask in TT? Other?)
  - DATE: PK text ISO8601 date
  - OPENED: text HHMM of when valet opened that day
  - CLOSED: HHMM of when valet closed that day
  - DAY: int 0-6 day of week (for convenience; calculate at load from DATE).  Or text day of week (sigh)
  - PRECIP: number, to be bulk-populated from Environment Canada records [can be null]
  - TEMP10AM: same  [can be null]
  - SUNSET: HHMM - calculated or bulk-populated  [can be null]
  - EVENT: free text - NULL if none, else statement, eg "orange shirt day" "election" "Vic Day parade".  Make it short - eg 50 chr max
  - EVENT_PROXIMITY: num -- estimated distance to EVENT in km
  - REGISTRATIONS: # of 529 registrations

And probably create some views that join this with the main table to include things like:
- bikes_leftover *
- max_full_regular *
- max_full_oversize *
- max_full_total *
- parked_regular *
- parked_oversize *
- parked_total *
- etc?

\* these ones might best be calculated and inserted into the DAILY_SUMMARY table as they would be nasty to calculate in a view.  If we were real DB-heads we would recalculate them using stored procedures as a trigger on commits to the details database.

Also: avoid mixed case in table names

**Comment by ironwoodcall** [comment]
Working on:
- [ ] Change guessing closing time to base only on last event with no time rounding
- [ ] Finish list of columns for `days` table
- [ ] Add insertion in to days table
- [ ] Filter all insertion activity to only very recent / yesterday
- [ ] Read tags.txt for bike types if no info in logfile
- [ ] Update handling for leftover bikes:
- check the day summaries table for a check-out time
- use as check-out for leftovers if it exists
- if not, record check-out as the same as the last bike checking out and flag as leftover in that column
- calculate stay duration


*might* add handling for double stays by the same tag -- need to change the ID format if so

**Comment by ironwoodcall** [comment]
addressed everything herein
